/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'startTime' : IDL.Int,
  'owner' : IDL.Principal,
  'note' : IDL.Text,
  'subTopicId' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'energyRating' : IDL.Text,
});
export const SubTopic = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const TodoItem = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
  'subTopicId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ImprovementNote = IDL.Record({
  'id' : IDL.Nat,
  'dateKey' : IDL.Text,
  'owner' : IDL.Principal,
  'note' : IDL.Text,
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [Category], []),
  'addSession' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Int, IDL.Nat, IDL.Text, IDL.Text],
      [Session],
      [],
    ),
  'addSubTopic' : IDL.Func([IDL.Nat, IDL.Text], [SubTopic], []),
  'addTodoItem' : IDL.Func([IDL.Nat, IDL.Text], [TodoItem], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteSubTopic' : IDL.Func([IDL.Nat], [], []),
  'deleteTodoItem' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllImprovementNotes' : IDL.Func(
      [],
      [IDL.Vec(ImprovementNote)],
      ['query'],
    ),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAllSubTopics' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getImprovementNoteByDateKey' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ImprovementNote)],
      ['query'],
    ),
  'getSessionsByTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Session)],
      ['query'],
    ),
  'getSubTopicsByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SubTopic)],
      ['query'],
    ),
  'getTodoItemsBySubTopic' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TodoItem)],
      ['query'],
    ),
  'getTotalSecondsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getTotalSecondsBySubTopic' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'toggleTodoItemCompleted' : IDL.Func([IDL.Nat], [TodoItem], []),
  'upsertImprovementNote' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ImprovementNote],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'startTime' : IDL.Int,
    'owner' : IDL.Principal,
    'note' : IDL.Text,
    'subTopicId' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'energyRating' : IDL.Text,
  });
  const SubTopic = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const TodoItem = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
    'subTopicId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ImprovementNote = IDL.Record({
    'id' : IDL.Nat,
    'dateKey' : IDL.Text,
    'owner' : IDL.Principal,
    'note' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [Category], []),
    'addSession' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Int, IDL.Nat, IDL.Text, IDL.Text],
        [Session],
        [],
      ),
    'addSubTopic' : IDL.Func([IDL.Nat, IDL.Text], [SubTopic], []),
    'addTodoItem' : IDL.Func([IDL.Nat, IDL.Text], [TodoItem], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteSubTopic' : IDL.Func([IDL.Nat], [], []),
    'deleteTodoItem' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllImprovementNotes' : IDL.Func(
        [],
        [IDL.Vec(ImprovementNote)],
        ['query'],
      ),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAllSubTopics' : IDL.Func([], [IDL.Vec(SubTopic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getImprovementNoteByDateKey' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImprovementNote)],
        ['query'],
      ),
    'getSessionsByTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Session)],
        ['query'],
      ),
    'getSubTopicsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SubTopic)],
        ['query'],
      ),
    'getTodoItemsBySubTopic' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TodoItem)],
        ['query'],
      ),
    'getTotalSecondsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getTotalSecondsBySubTopic' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'toggleTodoItemCompleted' : IDL.Func([IDL.Nat], [TodoItem], []),
    'upsertImprovementNote' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ImprovementNote],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };