/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
}
export interface ImprovementNote {
  'id' : bigint,
  'dateKey' : string,
  'owner' : Principal,
  'note' : string,
  'updatedAt' : bigint,
}
export interface Session {
  'id' : bigint,
  'categoryId' : bigint,
  'startTime' : bigint,
  'owner' : Principal,
  'note' : string,
  'subTopicId' : bigint,
  'durationSeconds' : bigint,
  'energyRating' : string,
}
export interface SubTopic {
  'id' : bigint,
  'categoryId' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
}
export interface TodoItem {
  'id' : bigint,
  'owner' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'completed' : boolean,
  'subTopicId' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], Category>,
  'addSession' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, string],
    Session
  >,
  'addSubTopic' : ActorMethod<[bigint, string], SubTopic>,
  'addTodoItem' : ActorMethod<[bigint, string], TodoItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteSubTopic' : ActorMethod<[bigint], undefined>,
  'deleteTodoItem' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllImprovementNotes' : ActorMethod<[], Array<ImprovementNote>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getAllSubTopics' : ActorMethod<[], Array<SubTopic>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getImprovementNoteByDateKey' : ActorMethod<[string], [] | [ImprovementNote]>,
  'getSessionsByTimeRange' : ActorMethod<[bigint, bigint], Array<Session>>,
  'getSubTopicsByCategory' : ActorMethod<[bigint], Array<SubTopic>>,
  'getTodoItemsBySubTopic' : ActorMethod<[bigint], Array<TodoItem>>,
  'getTotalSecondsByCategory' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getTotalSecondsBySubTopic' : ActorMethod<[], Array<[bigint, bigint]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'toggleTodoItemCompleted' : ActorMethod<[bigint], TodoItem>,
  'upsertImprovementNote' : ActorMethod<[string, string], ImprovementNote>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];